### ISSUE TITLE
A version with member sidebar not hidden?

### ISSUE THREAD

**Issue by KevWithADot** [DevEvil99/DarkPlus-Discord-Theme#1]
With the current theme, the member sidebar is hidden until a cursor is hovered over it. I want it to be always visible. Is there a function to do that?

**Comment by Sheytann** [comment]
Yes please same, can we have a version of it without the side bar hiding, please.

**Comment by DevEvil99** [comment]
Join my [Discord](https://dsc.gg/devevil) server and check English-support pins
