### ISSUE TITLE
Server's gif/banner

### ISSUE THREAD

**Issue by arinoki** [DevEvil99/DarkPlus-Discord-Theme#11]
Hello. With this theme this banner doesn't show. Can you update/fix please?

![image](https://github.com/DevEvil99/DarkPlus-Discord-Theme/assets/966158/b8bf434f-7164-433d-a9e8-8243b99f1d58)

**Comment by arinoki** [comment]
And if this matters - I use vencord.

**Comment by DevEvil99** [comment]
I will fix it
