### ISSUE TITLE
BetterDiscord preview URI Incorrectly formatted: Preview not working.

### ISSUE THREAD

**Issue by Ambushfall** [DevEvil99/DarkPlus-Discord-Theme#14]
Please update the BetterDiscord link following the Encoded URI Component pattern.

Dark+.theme.css should be Dark%2B.theme.css in the URI as the preview will not work otherwise.

[Example working preview](https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/DevEvil99/DarkPlus-Discord-Theme/Dark%2B.theme.css)

[Example current preview](https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/DevEvil99/DarkPlus-Discord-Theme/Dark+.theme.css)

**Comment by DevEvil99** [comment]
we cant change betterdiscord preview link
