### ISSUE TITLE
just members list

### ISSUE THREAD

**Issue by 7368697661** [DevEvil99/DarkPlus-Discord-Theme#22]
hey! sorry to bother you, but this theme is the only way ive found to have hover-members list on the right side. would there be any way to get a version with just the members list changes? ive been trying to go thru the source myself to figure it out but im not super sure what to look for. would this be possible? thanks anyway, super cool theme! great job :)

**Comment by 7368697661** [comment]
update:

i figured out this is the code for splitting the member list edits out, sorry if this steps on any toes!
```
.members_cbd271,
.membersWrap_cbd271, .container_cbd271 {
	min-width: 60px;
	transition-duration: 500ms;
	transition-property: box-shadow, min-width, width;
	width: 80px;
	z-index: 10;
    background: var(--bg-alt);
    border-left: 1px solid var(--border);
}

.members_cbd271:hover,
.membersWrap_cbd271:hover {
	min-width: 240px;
	width: 240px;
}

.membersWrap_cbd271 {
	height: 100%;
	position: absolute;
	right: 0;
}

.membersWrap_cbd271:hover {
	box-shadow: none;
}

.membersGroup_cbd271 {
	height: 0;
	transition-duration: 500ms;
	transition-property: height;
}

.members_cbd271:hover .membersGroup_cbd271 {
	height: 40px;
}
```

**Comment by DevEvil99** [comment]
You want the default memberlist?

**Comment by DevEvil99** [comment]
Closing this issue due to a lack of responses. Please feel free to reopen it if needed.
