### ISSUE TITLE
Account Details Issue

### ISSUE THREAD

**Issue by Sertule** [DevEvil99/DarkPlus-Discord-Theme#4]
![image_2022-05-02_205445498](https://user-images.githubusercontent.com/95261381/166390130-833e7b75-1d52-4194-a07e-47cd07757d1c.png)
The account details appear like this whenever I use the theme unfortunately, I'm on the most recent version as well.

**Comment by DevEvil99** [comment]
Disable AccountDetailsPlus plugin
