### ISSUE TITLE
Cannot change color card of other users

### ISSUE THREAD

**Issue by S0ULL355** [DevEvil99/DarkPlus-Discord-Theme#8]
The color card on other users is unchangeable for idiots (me)
![image](https://user-images.githubusercontent.com/48848185/196017935-6b923319-ff7c-4ece-9fbd-56fece409a24.png)
![image](https://user-images.githubusercontent.com/48848185/196017957-963481ab-fdf8-486a-bcea-5b0e75b2c971.png)

**Comment by DevEvil99** [comment]
the new update of BD and Discord broke many of my themes please be patient until they are fixed! NO ETA

also, if you find any bugs in my themes, send them to my dm to speed up the development

**Comment by DevEvil99** [comment]
fixed
